"""db init

Revision ID: e2411bfe9cdd
Revises: 
Create Date: 2023-07-30 17:15:01.608063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e2411bfe9cdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'course',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('dollar', sa.Float(), nullable=True),
        sa.Column('euro', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'gps_report_timestamp_device_id_idx',
        'course',
        [sa.text('date DESC')],
        unique=False,
    )
    op.create_index(op.f('ix_course_date'), 'course', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_date'), table_name='course')
    op.drop_index('gps_report_timestamp_device_id_idx', table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
