"""add task exeptions

Revision ID: fab643bcd398
Revises: e2411bfe9cdd
Create Date: 2023-07-30 19:23:41.586791

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fab643bcd398'
down_revision = 'e2411bfe9cdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'exceptions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('course', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_course_date', table_name='course')
    op.drop_index('gps_report_timestamp_device_id_idx', table_name='course')
    op.create_index(
        'gps_report_timestamp_device_id_idx',
        'course',
        [sa.text('created_at DESC')],
        unique=False,
    )
    op.create_index(op.f('ix_course_created_at'), 'course', ['created_at'], unique=False)
    op.drop_column('course', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'course',
        sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f('ix_course_created_at'), table_name='course')
    op.drop_index('gps_report_timestamp_device_id_idx', table_name='course')
    op.create_index(
        'gps_report_timestamp_device_id_idx',
        'course',
        [sa.text('date DESC')],
        unique=False,
    )
    op.create_index('ix_course_date', 'course', ['date'], unique=False)
    op.drop_column('course', 'created_at')
    op.drop_table('exceptions')
    # ### end Alembic commands ###
